#ifndef HALO_MACOS_POSIX_BACKEND_NAMES_H
#define HALO_MACOS_POSIX_BACKEND_NAMES_H

/* Native host backend names must not collide with recomp_import_aliases.c,
 * which exports the original posix_* spellings as guest import trampolines. */
#define posix_stat mac_native_posix_stat
#define posix_fstat mac_native_posix_fstat
#define posix_set_file_times mac_native_posix_set_file_times
#define posix_seek mac_native_posix_seek
#define posix_truncate mac_native_posix_truncate
#define posix_disk_space mac_native_posix_disk_space
#define posix_set_read_only mac_native_posix_set_read_only
#define posix_make_directory mac_native_posix_make_directory
#define posix_directory_open mac_native_posix_directory_open
#define posix_directory_next mac_native_posix_directory_next
#define posix_directory_close mac_native_posix_directory_close
#define posix_find_entry_case_insensitive mac_native_posix_find_entry_case_insensitive
#define posix_socket_last_error mac_native_posix_socket_last_error
#define posix_socket mac_native_posix_socket
#define posix_socket_close mac_native_posix_socket_close
#define posix_socket_bind mac_native_posix_socket_bind
#define posix_socket_connect mac_native_posix_socket_connect
#define posix_socket_listen mac_native_posix_socket_listen
#define posix_socket_accept mac_native_posix_socket_accept
#define posix_socket_send mac_native_posix_socket_send
#define posix_socket_sendto mac_native_posix_socket_sendto
#define posix_socket_recv mac_native_posix_socket_recv
#define posix_socket_recvfrom mac_native_posix_socket_recvfrom
#define posix_socket_shutdown mac_native_posix_socket_shutdown
#define posix_socket_set_nonblocking mac_native_posix_socket_set_nonblocking
#define posix_socket_bytes_available mac_native_posix_socket_bytes_available
#define posix_socket_set_nodelay mac_native_posix_socket_set_nodelay
#define posix_socket_setsockopt mac_native_posix_socket_setsockopt
#define posix_socket_getsockopt mac_native_posix_socket_getsockopt
#define posix_socket_getsockname mac_native_posix_socket_getsockname
#define posix_socket_getpeername mac_native_posix_socket_getpeername
#define posix_socket_select mac_native_posix_socket_select
#define posix_local_ipv4_address mac_native_posix_local_ipv4_address
#define posix_random_bytes mac_native_posix_random_bytes
#define posix_resolve_ipv4 mac_native_posix_resolve_ipv4
#define posix_command_line_argument mac_native_posix_command_line_argument
#define posix_process_id mac_native_posix_process_id
#define posix_register_url_scheme mac_native_posix_register_url_scheme
#define posix_discord_connect mac_native_posix_discord_connect
#define posix_discord_write mac_native_posix_discord_write
#define posix_discord_read mac_native_posix_discord_read
#define posix_discord_close mac_native_posix_discord_close

#define posix_upnp_forward_udp mac_native_posix_upnp_forward_udp
#define posix_upnp_stop_forwarding_udp mac_native_posix_upnp_stop_forwarding_udp

#endif
