#!/usr/bin/env python3
"""Generate deterministic 32-bit GL procedure tokens and wrapper signatures.

The AOT guest is i686 and cannot hold a native arm64 GL function pointer. This
tool derives the exported GL surface from port/linux/src/gl.h, reads exact host
prototypes from SDL's OpenGL headers, and emits a stable signature manifest
consumed by the typed wrapper generator and token registry.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

TOKEN_BASE = 0xFE100000
TOKEN_STRIDE = 16


def split_arguments(text: str) -> list[tuple[str, str]]:
    text = text.strip()
    if not text or text == "void":
        return []
    out = []
    for arg in text.split(","):
        arg = " ".join(arg.split())
        match = re.fullmatch(r"(.+?\*?\s*)([A-Za-z_][A-Za-z0-9_]*)", arg)
        if not match:
            raise ValueError(f"cannot parse GL parameter declaration: {arg}")
        ctype, name = match.groups()
        out.append((ctype.strip(), name))
    return out


def slot_count(ctype: str) -> int:
    # GLdouble/GLclampd are 64-bit values in the i686 cdecl ABI. GLsizeiptr
    # and GLintptr are pointer-sized on the guest, so occupy one 32-bit slot.
    return 2 if ctype in ("GLdouble", "GLclampd") else 1


def generate_wrappers(entries: list[dict[str, object]]) -> str:
    lines = [
        "/* Generated by tools/macos_gl_bridge.py. Do not edit. */",
        '#include <SDL3/SDL_opengl.h>',
        '#include "guest_call.h"',
        '#include "guest_address.h"',
        '#include "gl_token_registry.h"',
        '#include "recomp_types.h"',
        '#include <stdint.h>',
        '#include <stdlib.h>',
        '#include <string.h>',
        '#include <stdio.h>',
        '#include <pthread.h>',
        'extern void *mac_macos_gl_native_proc(const char *name);',
        'extern void *mac_macos_gl_guest_pointer(const char *name, unsigned arg_index, uint32_t guest_va, const uint32_t *raw_args, unsigned arg_count);',
        'extern uint32_t mac_macos_gl_return_guest_pointer(const char *name, const void *host_pointer, const uint32_t *raw_args, unsigned arg_count);',
        'extern void mac_macos_gl_bridge_fault(const char *name, const char *reason);',
        'typedef void (APIENTRYP mac_fbo_get_integer_fn)(GLenum, GLint *);',
        'typedef void (APIENTRYP mac_fbo_get_attachment_fn)(GLenum, GLenum, GLenum, GLint *);',
        'typedef void (APIENTRYP mac_fbo_get_tex_level_fn)(GLenum, GLint, GLenum, GLint *);',
        'typedef void (APIENTRYP mac_fbo_bind_texture_fn)(GLenum, GLuint);',
        'typedef void (APIENTRYP mac_fbo_get_renderbuffer_fn)(GLenum, GLenum, GLint *);',
        'typedef void (APIENTRYP mac_fbo_bind_renderbuffer_fn)(GLenum, GLuint);',
        'typedef GLenum (APIENTRYP mac_fbo_get_error_fn)(void);',
        'typedef void (APIENTRYP mac_tex_get_integer_fn)(GLenum, GLint *);',
        'typedef GLenum (APIENTRYP mac_tex_get_error_fn)(void);',
        'static void mac_trace_tex_image_2d(GLenum target, GLint level, GLint internal, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels)',
        '{',
        '\tif (!getenv("HALO_TRACE_TEX_IMAGE")) return;',
        '\tmac_tex_get_integer_fn get_integer = (mac_tex_get_integer_fn)mac_macos_gl_native_proc("glGetIntegerv");',
        '\tmac_tex_get_error_fn get_error = (mac_tex_get_error_fn)mac_macos_gl_native_proc("glGetError");',
        '\tGLint binding = 0;',
        '\tif (get_integer && target == GL_TEXTURE_2D) get_integer(GL_TEXTURE_BINDING_2D, &binding);',
        '\tfprintf(stderr, "[tex-image] target=0x%04x texture=%d level=%d internal=0x%04x size=%dx%d border=%d format=0x%04x type=0x%04x pixels=%p\\n", target, binding, level, internal, width, height, border, format, type, pixels);',
        '\tif (get_error) fprintf(stderr, "[tex-image] glErrorAfterUpload=0x%04x\\n", get_error());',
        '}',
        'static void mac_trace_fbo_check(GLenum target, GLenum status)',
        '{',
        '\tif (!getenv("HALO_TRACE_FBO")) return;',
        '\tmac_fbo_get_integer_fn get_integer = (mac_fbo_get_integer_fn)mac_macos_gl_native_proc("glGetIntegerv");',
        '\tmac_fbo_get_attachment_fn get_attachment = (mac_fbo_get_attachment_fn)mac_macos_gl_native_proc("glGetFramebufferAttachmentParameteriv");',
        '\tmac_fbo_get_tex_level_fn get_tex_level = (mac_fbo_get_tex_level_fn)mac_macos_gl_native_proc("glGetTexLevelParameteriv");',
        '\tmac_fbo_bind_texture_fn bind_texture = (mac_fbo_bind_texture_fn)mac_macos_gl_native_proc("glBindTexture");',
        '\tmac_fbo_get_renderbuffer_fn get_renderbuffer = (mac_fbo_get_renderbuffer_fn)mac_macos_gl_native_proc("glGetRenderbufferParameteriv");',
        '\tmac_fbo_bind_renderbuffer_fn bind_renderbuffer = (mac_fbo_bind_renderbuffer_fn)mac_macos_gl_native_proc("glBindRenderbuffer");',
        '\tmac_fbo_get_error_fn get_error = (mac_fbo_get_error_fn)mac_macos_gl_native_proc("glGetError");',
        '\tGLint framebuffer = 0;',
        '\tGLint old_texture = 0, old_renderbuffer = 0;',
        '\tif (!get_integer || !get_attachment) { fprintf(stderr, "[fbo-trace] status=0x%04x target=0x%04x metadata-procs-missing\\n", status, target); return; }',
        '\t/* Local static address from the pinned 2b0c27cb guest ELF; refresh with each relink. */',
        '\tuint32_t scale_x_bits = MEM32(0x005A6514u), scale_y_bits = MEM32(0x005A6518u); float scale_x, scale_y; memcpy(&scale_x, &scale_x_bits, sizeof(scale_x)); memcpy(&scale_y, &scale_y_bits, sizeof(scale_y));',
        '\tfprintf(stderr, "[fbo-trace] guest-screen-scale bits={0x%08x,0x%08x} values={%.9g,%.9g}\\n", scale_x_bits, scale_y_bits, scale_x, scale_y);',
        '\tget_integer(target == GL_READ_FRAMEBUFFER ? GL_READ_FRAMEBUFFER_BINDING : GL_DRAW_FRAMEBUFFER_BINDING, &framebuffer);',
        '\tfprintf(stderr, "[fbo-trace] target=0x%04x fbo=%d status=0x%04x\\n", target, framebuffer, status);',
        '\tconst GLenum points[] = { GL_COLOR_ATTACHMENT0, GL_DEPTH_STENCIL_ATTACHMENT };',
        '\tfor (size_t i = 0; i < sizeof(points) / sizeof(points[0]); ++i) {',
        '\t\tGLint type = GL_NONE, object = 0, level = 0, width = 0, height = 0, internal = 0;',
        '\t\tget_attachment(target, points[i], GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE, &type);',
        '\t\tget_attachment(target, points[i], GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME, &object);',
        '\t\tif (type == GL_TEXTURE && object && get_integer && get_tex_level && bind_texture) {',
        '\t\t\tget_attachment(target, points[i], GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL, &level);',
        '\t\t\tget_integer(GL_TEXTURE_BINDING_2D, &old_texture); bind_texture(GL_TEXTURE_2D, (GLuint)object);',
        '\t\t\tget_tex_level(GL_TEXTURE_2D, level, GL_TEXTURE_WIDTH, &width); get_tex_level(GL_TEXTURE_2D, level, GL_TEXTURE_HEIGHT, &height); get_tex_level(GL_TEXTURE_2D, level, GL_TEXTURE_INTERNAL_FORMAT, &internal);',
        '\t\t\tbind_texture(GL_TEXTURE_2D, (GLuint)old_texture);',
        '\t\t} else if (type == GL_RENDERBUFFER && object && get_integer && get_renderbuffer && bind_renderbuffer) {',
        '\t\t\tget_integer(GL_RENDERBUFFER_BINDING, &old_renderbuffer); bind_renderbuffer(GL_RENDERBUFFER, (GLuint)object);',
        '\t\t\tget_renderbuffer(GL_RENDERBUFFER, GL_RENDERBUFFER_WIDTH, &width); get_renderbuffer(GL_RENDERBUFFER, GL_RENDERBUFFER_HEIGHT, &height); get_renderbuffer(GL_RENDERBUFFER, GL_RENDERBUFFER_INTERNAL_FORMAT, &internal);',
        '\t\t\tbind_renderbuffer(GL_RENDERBUFFER, (GLuint)old_renderbuffer);',
        '\t\t}',
        '\t\tfprintf(stderr, "[fbo-trace] attachment=0x%04x type=0x%04x object=%d level=%d size=%dx%d internal=0x%04x\\n", points[i], type, object, level, width, height, internal);',
        '\t}',
        '\tif (get_error) fprintf(stderr, "[fbo-trace] glErrorAfterMetadata=0x%04x\\n", get_error());',
        '}',
    ]
    registry = []
    for entry in entries:
        name = str(entry["name"])
        token = int(entry["token"])
        ret = str(entry["return_type"])
        args_text = str(entry["arguments"])
        args = split_arguments(args_text)
        arg_decl = ", ".join(f"{ctype} a{index}" for index, (ctype, _) in enumerate(args)) or "void"
        arg_names = ", ".join(f"a{index}" for index in range(len(args)))
        lines.append(f"typedef {ret} (APIENTRYP mac_fn_{name})({arg_decl});")
        lines.append(f"void sub_{token:08X}(void)")
        lines.append("{")
        # `recomp_types.h` defines the generated-code alias `esp` as `g_esp`.
        # Do not name this wrapper-local snapshot `esp`: after preprocessing,
        # `uint32_t esp = g_esp` becomes a self-initializing local `g_esp`,
        # so argument reads use an indeterminate stack address and the return
        # silently updates the local instead of translator TLS.
        lines.append("\tuint32_t guest_entry_esp = g_esp;")
        words = sum(slot_count(ctype) for ctype, _ in args)
        lines.append(f"\tuint32_t stack_words[{max(words, 1)}] = {{ 0 }};")
        lines.append(f"\tuint32_t raw[{max(len(args), 1)}] = {{ 0 }};")
        lines.append("\t(void)raw;")
        lines.append("\t(void)stack_words;")
        lines.append("\tuint32_t next_esp;")
        if name == "glGetString":
            lines.append("\tif (getenv(\"HALO_TRACE_GUEST_STACK\"))")
            lines.append("\t{ uint32_t _arg_va = guest_entry_esp + 4u; uint32_t _ret = 0; (void)mac_guest_stack_return(guest_entry_esp, &_ret);")
            lines.append("\t\tfprintf(stderr, \"[GL-ENTRY] name=glGetString thread=%llu entry_esp=0x%08x caller_pre_esp=0x%08x ebp=0x%08x mem_offset=%td ret=0x%08x arg_va=0x%08x arg_host=%p\\n\", (unsigned long long)(uintptr_t)pthread_self(), guest_entry_esp, guest_entry_esp + 4u, g_ebp, g_xbox_mem_offset, _ret, _arg_va, mac_guest_address_resolve(_arg_va, 4)); fflush(stderr); }\n")
        word = 0
        arg_words = []
        for index, (ctype, arg_name) in enumerate(args):
            nslots = slot_count(ctype)
            for component in range(nslots):
                lines.append(f"\tif (mac_guest_stack_arg32(guest_entry_esp, {word + component}, &stack_words[{word + component}]) != 0)")
                lines.append(f"\t\tmac_macos_gl_bridge_fault(\"{name}\", \"guest argument stack is unmapped\");")
            lines.append(f"\traw[{index}] = stack_words[{word}];")
            arg_words.append(word)
            word += nslots
        locals_ = []
        for index, (ctype, arg_name) in enumerate(args):
            nslots = slot_count(ctype)
            word = arg_words[index]
            local = f"a{index}"
            if "*" in ctype:
                lines.append(f"\t{ctype} {local} = ({ctype})mac_macos_gl_guest_pointer(\"{name}\", {index}, raw[{index}], raw, {len(args)});")
                lines.append(f"\tif (raw[{index}] && !{local}) mac_macos_gl_bridge_fault(\"{name}\", \"guest pointer span is invalid or unsupported\");")
            elif nslots == 2:
                lines.append(f"\tuint64_t bits_{index} = (uint64_t)stack_words[{word}] | ((uint64_t)stack_words[{word + 1}] << 32);")
                lines.append(f"\t{ctype} {local};")
                lines.append(f"\tmemcpy(&{local}, &bits_{index}, sizeof({local}));")
            elif ctype in ("GLfloat", "GLclampf"):
                lines.append(f"\t{ctype} {local};")
                lines.append(f"\tmemcpy(&{local}, &stack_words[{word}], sizeof({local}));")
            elif ctype in ("GLsizeiptr", "GLintptr"):
                lines.append(f"\t{ctype} {local} = ({ctype})(int32_t)stack_words[{word}];")
            else:
                lines.append(f"\t{ctype} {local} = ({ctype})stack_words[{word}];")
            locals_.append(local)
        lines.append(f"\tmac_fn_{name} fn = (mac_fn_{name})mac_macos_gl_native_proc(\"{name}\");")
        lines.append(f"\tif (!fn) mac_macos_gl_bridge_fault(\"{name}\", \"native GL entry point is unavailable\");")
        call = f"fn({arg_names})" if args else "fn()"
        if ret == "void":
            lines.append(f"\t{call};")
            if name == "glTexImage2D":
                lines.append("\tmac_trace_tex_image_2d(a0, a1, a2, a3, a4, a5, a6, a7, a8);")
        elif "*" in ret:
            lines.append(f"\t{ret} result = {call};")
            lines.append(f"\tg_eax = mac_macos_gl_return_guest_pointer(\"{name}\", (const void *)result, raw, {len(args)});")
        else:
            lines.append(f"\t{ret} result = {call};")
            if name == "glCheckFramebufferStatus":
                lines.append("\tmac_trace_fbo_check(a0, (GLenum)result);")
            lines.append("\tg_eax = (uint32_t)result;")
        lines.append("\tif (mac_guest_stack_after_return(guest_entry_esp, 0, &next_esp) != 0)")
        lines.append(f"\t\tmac_macos_gl_bridge_fault(\"{name}\", \"cannot pop guest cdecl return address\");")
        lines.append("\tg_esp = next_esp;")
        lines.append("}")
        registry.append((name, token))
    lines.extend([
        "struct mac_macos_gl_token_entry { const char *name; uint32_t token; mac_macos_gl_guest_function wrapper; };",
        "static const struct mac_macos_gl_token_entry mac_gl_tokens[] = {",
    ])
    lines.extend(f'\t{{ "{name}", 0x{token:08X}u, sub_{token:08X} }},' for name, token in registry)
    lines.extend([
        "};",
        "uint32_t mac_macos_gl_token_for_name(const char *name)",
        "{",
        "\tif (!name) return 0;",
        "\tfor (size_t i = 0; i < sizeof(mac_gl_tokens) / sizeof(mac_gl_tokens[0]); i++)",
        "\t\tif (strcmp(name, mac_gl_tokens[i].name) == 0) return mac_gl_tokens[i].token;",
        "\treturn 0;",
        "}",
        "mac_macos_gl_guest_function mac_macos_gl_wrapper_for_token(uint32_t token)",
        "{",
        "\tfor (size_t i = 0; i < sizeof(mac_gl_tokens) / sizeof(mac_gl_tokens[0]); i++)",
        "\t\tif (token == mac_gl_tokens[i].token) return mac_gl_tokens[i].wrapper;",
        "\treturn NULL;",
        "}",
    ])
    return "\n".join(lines) + "\n"


def gl_names(gl_header: Path) -> list[str]:
    text = gl_header.read_text()
    marker = "#define GL_FUNCTIONS(X)"
    start = text.find(marker, text.find("#else\n#ifdef HALO_MACOS"))
    if start < 0:
        raise ValueError("could not find desktop GL_FUNCTIONS list")
    end = text.find("\n#endif", start)
    if end < 0:
        raise ValueError("unterminated desktop GL_FUNCTIONS list")
    block = text[start:end]
    names = re.findall(r"\bX\((gl[A-Za-z0-9_]+)\)\s*\\?", block)
    if not names or len(names) != len(set(names)):
        raise ValueError("GL function list is empty or contains duplicates")
    return names


def prototypes(paths: list[Path]) -> dict[str, tuple[str, str]]:
    # SDL's generated headers use either `GLAPIENTRY` or `APIENTRY`; whitespace
    # around pointer return types varies, so match declaration through semicolon.
    pattern = re.compile(
        r"\bGLAPI\s+(.+?)(?:\s*GLAPIENTRY|\s*APIENTRY)\s+"
        r"(gl[A-Za-z0-9_]+)\s*\((.*?)\)\s*;", re.S
    )
    found: dict[str, tuple[str, str]] = {}
    for path in paths:
        for match in pattern.finditer(path.read_text()):
            ret, name, args = match.groups()
            found.setdefault(name, (" ".join(ret.split()), " ".join(args.split())))
    return found


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--gl-header", type=Path, required=True)
    parser.add_argument("--sdl-header", type=Path, action="append", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--c-output", type=Path)
    args = parser.parse_args()

    names = gl_names(args.gl_header)
    decls = prototypes(args.sdl_header)
    missing = [name for name in names if name not in decls]
    if missing:
        raise SystemExit("missing SDL host prototypes: " + ", ".join(missing))

    entries = []
    for index, name in enumerate(names):
        ret, signature = decls[name]
        split_arguments(signature)
        entries.append({
            "name": name,
            "token": TOKEN_BASE + index * TOKEN_STRIDE,
            "return_type": ret,
            "arguments": signature,
        })
    payload = {
        "format": 1,
        "token_base": TOKEN_BASE,
        "token_stride": TOKEN_STRIDE,
        "source_gl_header_sha256": hashlib.sha256(args.gl_header.read_bytes()).hexdigest(),
        "entries": entries,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2) + "\n")
    if args.c_output:
        args.c_output.parent.mkdir(parents=True, exist_ok=True)
        args.c_output.write_text(generate_wrappers(entries))
    print(f"wrote {len(entries)} deterministic GL token signatures to {args.output}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (OSError, ValueError) as error:
        raise SystemExit(str(error))
